- name: Configure HAPROXY
  hosts: proxy
  roles:
    - geerlingguy.haproxy
  vars:
    haproxy_frontend_port: 80
    haproxy_frontend_mode: 'http'
    haproxy_backend_balance_method: 'roundrobin'
    haproxy_backend_servers:
      - name: webserver1
        address: 192.168.33.12:80
      - name: webserver2
        address: 192.168.33.13:80
  tasks:
    - name: Ensure firewalld and its dependencies are installed
      yum:
        name: firewalld
        state: latest
    - name: Ensure firewalld is running
      service:
        name: firewalld
        state: started
        enabled: yes
    - name: Ensure firewalld is allowing to the traffic
      firewalld:
        port: 80/tcp
        permanent: yes
        immediate: yes
        state: enabled