- hosts: all
  vars_files: 
    - vars/user_list.yml
    - secret.yml
  tasks:
  - name: Create users on 'Webservers'
    user:
      name: "{{ item.username }}"
      group: "wheel"
      shell: "/bin/bash"
      uid: "{{ item.uid }}"
      createhome: yes
    with_items: '{{users}}'
    when: item.uid > 1000 and item.uid < 2000 and 'webservers' in group_names
  - name: Create users on 'database'
    user:
      name: "{{ item.username }}"
      password: "{{ user_password | password_hash('sha512')}}"
      group: "wheel"
      shell: "/bin/bash"
      uid: "{{ item.uid }}"
      createhome: yes
    with_items: '{{users}}'
    when: item.uid > 2000 and item.uid < 3000 and 'database' in group_names
  - name: Config SSH on 'Webservers'
    authorized_key:
      user: "{{ item.username }}"
      state: present
      key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"  
    with_items: " {{ users }}"
    when: item.uid > 1000 and item.uid < 2000 and 'webservers' in group_names
  - name: Config SSH on 'database
    authorized_key:
      user: "{{ item.username }}"
      state: present
      key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"  
    with_items: " {{ users }}"
    when: item.uid > 2000 and item.uid < 3000 and 'database' in group_names