- hosts: all
  vars_files: 
    - vars/user_list.yml
    - secret.yml
  tasks:
  - name: Check if group exists
    shell: /usr/bin/getent group | awk -F":" '{print $1}'
    register: etc_groups
    
  - name: Create users on 'Webservers'
    user:
      name: "{{ item.username }}"
      password: "{{ user_password | password_hash('sha512')}}"
      group: "wheel"
      shell: "/bin/bash"
      uid: "{{ item.uid }}"
      createhome: yes
    with_items: '{{users}}'
    when: 
      - "item.uid | string | first == '1'"
      - "'webservers' in group_names"
      - "'wheel' in etc_groups.stdout_lines"
  - name: Create users on 'database'
    user:
      name: "{{ item.username }}"
      password: "{{ user_password | password_hash('sha512')}}"
      group: "wheel"
      shell: "/bin/bash"
      uid: "{{ item.uid }}"
      createhome: yes
    with_items: '{{users}}'
    when: 
      - "item.uid | string | first == '2'"
      - "'database' in group_names"
      - "'wheel' in etc_groups.stdout_lines"
  - name: Config SSH on 'Webservers'
    authorized_key:
      user: "{{ item.username }}"
      state: present
      key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"  
    with_items: " {{ users }}"
    when: 
      - "item.uid | string | first == '1'"
      - "'webservers' in group_names"
      - "'wheel' in etc_groups.stdout_lines"
  - name: Config SSH on 'database
    authorized_key:
      user: "{{ item.username }}"
      state: present
      key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"  
    with_items: " {{ users }}"
    when: 
      - "item.uid | string | first == '2'"
      - "'database' in group_names"
      - "'wheel' in etc_groups.stdout_lines"
