- hosts: proxy
  tasks:
  - name: Creates a cron file under /etc/cron.d
    cron:
      name: 
      minute: 0
      hour: "*"
      day: "*"
      month: "*"
      weekday: "*"
      user: root
      job: "date >> /var/log/time.log"
      cron_file: ansible_date_log