- hosts: proxy
  tasks:
  - name: Creates a cron file under /etc/cron.d
    cron:
      name: 
      special_time: hourly
      user: root
      job: "date >> /var/log/time.log"
  - name: Check cron
    shell: crontab -l
    register: ps
  - debug: var=ps.stdout_lines
