- hosts: all
  tasks:
    - name: Install pachages on proxy
      yum:
        name: ['tcpdump', 'mailx']
        state: latest 
      when: inventory_hostname in groups['proxy']
    - name: Install pachages on database
      yum:
        name: ['lsof', 'mailx']
        state: latest 
      when: inventory_hostname in groups['database']