- hosts: all
  tasks:
  - name: Set SSH Banner
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^Banner "
      line: "Banner /etc/motd"
  - name: Disabling X11 Forwarding  
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^X11Forwarding'
      line: 'X11Forwarding no'
  - name: Set SSH MaxAuthTries to 3
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^MaxAuthTries "
      line: "MaxAuthTries 3"
  - name: Restart ssh
    service:
      name: sshd
      state: restarted
      enabled: yes