- hosts: all
  tasks:
  - name: Template a file 
    template:
      src: sudoers.j2
      dest: "/etc/sudoers.d/sudoers"
      mode: 0440
      owner: root
      group: root
      validate: "/sbin/visudo -cf"